### ISSUE TITLE
AdlsClient.CreateClient(FQDN, credentilas) throws exception if FQDN == " https://someName.dfs.core.windows.net/", 

### ISSUE THREAD

**Issue by vit100** [Azure/azure-data-lake-store-net#37]
`
var adlsClient = AdlsClient.CreateClient("https://SOMENAME_FROM_PORTAL.dfs.core.windows.net", credentials);`

where SOMENAME_FROM_PORTAL is taken from "Storage Account -> Properties -> Primary ADLS file system endpoint"

Exception:
`System.ArgumentException
  HResult=0x80070057
  Message=Account name https://SOMENAME_FROM_PORTAL.dfs.core.windows.net is invalid. Specify the full account including the domain name.
  Source=Microsoft.Azure.DataLake.Store
  StackTrace:
   at Microsoft.Azure.DataLake.Store.AdlsClient..ctor(String accnt, Int64 clientId, Boolean skipAccntValidation)
   at Microsoft.Azure.DataLake.Store.AdlsClient.CreateClient(String accountFqdn, ServiceClientCredentials creds)
   at batchHasher.Program.<Main>d__0.MoveNext() in C:\Dev\batchHasher\Program.cs:line 53
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\307\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in E:\A\_work\307\s\src\mscorlib\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 155
   at batchHasher.Program.<Main>(String[] args)
`

**Comment by rahuldutta90** [comment]
FQDN is "someName.dfs.core.windows.net"

**Comment by vit100** [comment]
u mean without "https://"?

**Comment by rahuldutta90** [comment]
yes

**Comment by rahuldutta90** [comment]
Also this is a adls gen2 account, and this sdk is for adls gen1.

**Comment by vit100** [comment]
oh well. my bad. probably docs need to be updated to say it explicitly.
